import type { NextPage } from 'next'

//Permission
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//File
import About from '../components/about/About'
import Blogpost from '../components/blogpost/Blogpost'
import Contact from '../components/contact/Contact'
import MyProject from '../components/myproject/MyProject'


//Home
const Home: NextPage = () => {
  return (
    <main className='bg-top bg-cover bg-no-repeat bg-fixed w-screen h-full'
      style={{backgroundImage : 'url(/assests/img/Background.jpg)'}}>
      
      {/*Title*/}
      <title>Wiku Wiki</title>
      <link rel="icon" href="/favicon.ico" />
      
      {/*Padding*/}
      <div className='px-2 sm:px-8 md:px-10 lg:px-48 xl:px-50'>

        {/*Profile*/}
        <div className="min-h-screen flex flex-col justify-center items-center ">
          <Image
            src="/assests/img/MyFace.png"
            width="220"
            height="220"
            alt="avatar"
          />
          <div className='text-center font-semibold text-3xl px-9 py-9'>
            <h1 className='mb-4'>DEWA MADE WIDYA KUSUMA</h1>
            <h3>Front-End Trainee at Taksu Teknologi Bali</h3>
          </div>
        </div>


        {/*Components*/}
        <div>
        <About></About>
        <MyProject></MyProject>
        <Blogpost></Blogpost>
        </div>
          

        {/*Footer*/}
        {/* <footer className={styles.footer}>
        <Contact></Contact>
          <h1>Powered by </h1>
        </footer> */}


      </div>

      <footer>
        <Contact></Contact>
        <div className='text-center'>
          <h1>Powered by </h1>
        </div>
      </footer>
    </main>
    

  )
}

export default Home

      {/*  
      <header className={styles.header}>
        <a>Home </a><a>About me </a><a>My Project </a><a>Blogpost </a><a>Contact </a>
      </header>
      */}

      {/* <main className={styles.main}>
        <Image
          src="/assests/img/MyFace.png"
          width="170"
          height="170"
          alt="avatar"
        />
        <h1 className={styles.title}>Dewa Made Widya Kusuma</h1>
        <h3>        Front-End Trainee at Taksu Teknologi Bali</h3>
      </main> */}
/* template from next js
  return (
    <div className={styles.container}>
      <Head>
        <title>Wiku Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <a href="components/About.tsx">
          <a>Click Here</a>
        </a>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
  */