import type { NextPage } from 'next'

import Image from 'next/image'
import styles from '../styles/Home.module.css'




import About from '../components/about/About'
import Blogpost from '../components/blogpost/Blogpost'
import Contact from '../components/contact/Contact'
import MyProject from '../components/myproject/MyProject'



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <title>Wiku Wiki</title>
      <link rel="icon" href="/favicon.ico" />

 {/*  
      <header className={styles.header}>
        <a>Home </a><a>About me </a><a>My Project </a><a>Blogpost </a><a>Contact </a>
      </header>
*/}

      <main className={styles.main}>
        <Image
          src="/assests/img/MyFace.png"
          width="170"
          height="170"
          alt="avatar"
        />
        <h1 className={styles.title}>Dewa Made Widya Kusuma</h1>
        <h3>        Front-End Trainee at Taksu Teknologi Bali</h3>
      </main>

      <About></About>
      <MyProject></MyProject>
      <Blogpost></Blogpost>
      <Contact></Contact>

      <footer className={styles.footer}>
        <h1>Powered by</h1>
      </footer>
    </div>
  )

/* template from next js
  return (
    <div className={styles.container}>
      <Head>
        <title>Wiku Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <a href="components/About.tsx">
          <a>Click Here</a>
        </a>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
  */
}

export default Home